"""Init

Revision ID: 7dbd714638a7
Revises: 62f1812de680
Create Date: 2024-04-10 20:17:16.914493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dbd714638a7'
down_revision: Union[str, None] = '62f1812de680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'additional_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('additional_data', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
